# Default values for js-chart
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.25"

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 80

deployment:
  enabled: true
  annotations: {}
  env:
    - name: ENVIRONMENT
      value: "production"


secret:
  enabled: true
  password: "my-secret-password"
  apiKey: "my-api-key-12345"

configMap:
  enabled: true

resources: {}
